export const toWhyWaveHome = () => "/why-wave-europe";
export const toContact = () => "/contact";
export const toReferenc = () => "/referenc";
export const toBusines = () => "/busines-consulting";
export const toCyber = () => "/cyber-security";
export const toIt = () => "/IT-recruitment";
export const toOutSours = () => "/outsourcing";
export const toSoft = () => "/software-development";
export const toTeam = () => "/team-setting-IT";
